oauth:
  naver:
    secret: ZP2xGYxKSn
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
  kakao:
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  google:
    secret: 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
    url:
      auth: https://oauth2.googleapis.com
      api: https://people.googleapis.com
