oauth:
  naver:
    secret: ZP2xGYxKSn
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
  kakao:
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
