spring:
  datasource:
    url: jdbc:mysql://gogo-rds-mysql.czf8aasuy3dy.ap-northeast-2.rds.amazonaws.com:3306/gogo_mysql?serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: admin
    password: 1324qewr!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # Entity 변경할 때만 수정하기
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
